# Generated by Django 5.0.3 on 2024-10-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0002_projectmembership_project_members_projectrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='role_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
