# Generated by Django 5.0.3 on 2024-10-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0003_projectrole_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrole',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='text',
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
